### ISSUE TITLE
Expiry can orphan cache

### ISSUE THREAD

**Issue by smdern** [ZJONSSON/cache-stampede#5]
Expired cache keys are only removed on `get`. When using Redis, there is no TTL, so it's very easy to have a cache leak where keys are never cleaned up and because TTL isn't set, volatile-lru can't remove any keys.

I'm going to look into using [`setex`](http://redis.io/commands/SETEX) for settings keys when an expiry is specified, but first wanted to check with you if there are any issues you can think that I could run into.

 It looks like `get` on an expired cache key removes it and then returns the same `NOT FOUND` error, so I'm assuming that using `setex` shouldn't cause any weird behaviour. Thoughts?

**Comment by ZJONSSON** [comment]
Thanks @smdern, yes the expiry is only checked/removed on `.get` - so you can easily end up with a bunch of expired data if nobody requested it again.   Not a problem for mongo (if you have enough diskspace) but for redis it can easily blow up memory.

Using `setex` seems like a very efficient way to keep redis cache size in check - I wonder if we can both have `setex` and the current expiry mechanism (which allows you effectively to execute modified expiry, i.e. different expiry in new requests than was original specified when data was saved)?

In any case if you find a nice way to do this then a PR would be much appreciated

**Comment by smdern** [comment]
Awesome! My plan was to keep the expiry meta data w/ the cached value because redis TTLs are in seconds, the expiry can be rounded up to the nearest second and still respect shorter expiries via the existing cache mechanism.

Thanks for the feedback!

**Comment by smdern** [comment]
https://github.com/ZJONSSON/cache-stampede/pull/6

**Comment by ZJONSSON** [comment]
closed with https://github.com/ZJONSSON/cache-stampede/pull/6
